FROM openjdk:17.0.2
ARG JAR_FILE=build/libs/prolog-1.0.0.jar
ENV MYSQL_URL=${SPRING_DATASOURCE_URL} \
MYSQL_USERNAME=${SPRING_DATASOURCE_USERNAME} \
MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
COPY ${JAR_FILE} prolog.jar
ENTRYPOINT ["java", "-jar", "/prolog.jar"]