FROM openjdk:17.0.2
ARG JAR_FILE=build/libs/prolog-1.0.0.jar
ENV MYSQL_URL=${SPRING_DATASOURCE_URL} \
MYSQL_USERNAME=${SPRING_DATASOURCE_USERNAME} \
MYSQL_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD} \
JWT_ISSUER=${JWT_ISSUER} \
JWT_SECRET_KEY=${JWT_SECRET_KEY} \
CLIENT_ID=${CLIENT_ID} \
CLIENT_SECRET=${CLIENT_SECRET} \
HOST=${HOST}
COPY ${JAR_FILE} prolog.jar
ENTRYPOINT ["java", "-jar", "/prolog.jar"]
