# default
spring:
  # 연결 DB 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${db.datasource.url}
    username: ${db.datasource.username}
    password: ${db.datasource.password}
    # 커넥션 풀 설정
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: MYSQL_DB

  # JPA 설정
  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: true
    baseline-on-migrate: true

--- # local
spring.config.activate.on-profile: "db-local"

# SQL 로그 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 파라미터 값

--- # prod
spring:
  config.activate.on-profile: "db-prod"

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true