spring:
  profiles:
    active:
      - prod
    group:
      local:
        - db-local
      prod:
        - db-prod

    include:
      - db
      - exception
      - security

management:
  endpoints:
    web:
      exposure:
        include: '*'