# default
spring:

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    # 커넥션 풀 설정
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5
      pool-name: MYSQL_DB

  # JPA 설정
  jpa:
    database: mysql
    generate-ddl: false
    open-in-view: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true

  flyway:
    enabled: false

  messages:
    encoding: UTF-8
    basename: messages/exceptions/exception, messages/logs/log-form

--- # local
spring:
  config.activate.on-profile: "db-local"

  datasource:
    url: ${db.datasource.url}
    username: ${db.datasource.username}
    password: ${db.datasource.password}

# SQL 로그 설정
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace # 파라미터 값

--- # prod
spring:
  config:
    activate.on-profile: "db-prod"
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql//localhost:3306/prolog
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_ROOT_PASSWORD}

  # Flyway 설정
  flyway:
    enabled: true
    baseline-on-migrate: true