name: Docker Build and Push & Run AWS

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create mysql docker container
        run: sudo docker run -d -p 3306:3306 --env MYSQL_DATABASE="${{ secrets.MYSQL_DATABASE }}" --env MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" mysql:8.0.23

      - name: Create db config file
        run: echo "${{ secrets.DB_PROPERTIES }}" > ./src/main/resources/db/db.properties

      - name: Build with Gradle
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: build

      - name: Docker build and push
        run: |
          docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker build -t fortune00/prolog .
          docker push fortune00/prolog:latest

      #      - name: Login to DockerHub
      #        uses: docker/login-action@v1
      #        with:
      #          username: ${{secrets.DOCKERHUB_USERNAME}}
      #          password: ${{secrets.DOCKERHUB_PASSWORD}}
      #
      #      - name: Build and Push
      #        uses: docker/build-push-action@v3
      #        with:
      #          context: .
      #          file: Dockerfile
      #          push: true
      #          tags: fortune00/prolog:latest

      - name: Access aws server and run the app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ${{ secrets.AWS_USERNAME }}
          key: ${{ secrets.AWS_KEY }}
          script: |
            sudo docker-compose down
            sudo docker pull fortune00/prolog
            echo "${{ secrets.DOCKER_COMPOSE }}" > ./docker-compose.yml
            echo "${{ secrets.DOCKER_COMPOSE_ENV }}" > ./.env
            sudo docker-compose up -d