name: Docker Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Create mysql docker container
        run: sudo docker run -d -p 3306:3306 --env MYSQL_DATABASE="${{ secrets.MYSQL_DATABASE }}" --env MYSQL_ROOT_PASSWORD="${{ secrets.MYSQL_ROOT_PASSWORD }}" mysql:8.0.23

      - uses: actions/checkout@v3
      - run: echo "${{ secrets.DOCKER }}" > ./.env
      - run: echo "${{ secrets.APP }}" > ./src/main/resources/db/db.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Project
        run: ./gradlew build

      - name: build and push
        run: |
          docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker build -t fortune00/prolog .
          docker push fortune00/prolog:latest

#      - name: Login to DockerHub
#        uses: docker/login-action@v1
#        with:
#          username: ${{secrets.DOCKERHUB_USERNAME}}
#          password: ${{secrets.DOCKERHUB_PASSWORD}}
#
#      - name: Build and Push
#        uses: docker/build-push-action@v3
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: fortune00/prolog:latest